---
name: release website
on:
  push:
    branches: [realm]
jobs:
  build-and-release:
    name: Build App and release
    runs-on: ubuntu-latest
    env:
      BUCKET: shikengno.xyz
      DIST: build
      REGION: us-east-1
      DIST_ID: E2QCBQ7SURRYU8
      REPO_COSMJS: https://github.com/cosmos/cosmjs.git

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}
    
    - name: Install dependencies
      run: |
        node --version
        npm ci --production

    - name: Add missing ts in dependencies
      run:  |
        git clone ${{env.REPO_COSMJS}}
        for p in amino crypto encoding ledger-amino math utils
          do
            echo "    Adding node_modules/@cosmjs/$p"
            cp -r cosmjs/packages/$p/src node_modules/cosmjs/$p
          done
        rm -rf cosmjs
    - name: Build website
      run: npm build

    - name: Delete old files to AWS
      run: |
        aws s3 sync --delete ${{ env.DIST_ID }} s3://${{ env.BUCKET }}

    - name: Adding updated files to AWS
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"